IABC/urls.py
from django.contrib import admin
from django.urls import path, include
from members.views import register_view, bidder_register_view, staff_register_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('django.contrib.auth.urls')),
    path('', include('members.urls')),
    path('IABC_WEB/', include('IABC_WEB.urls')),
    path('register/', register_view, name="register"),
    path('bidder_register/', bidder_register_view, name="bidder_register"),
    path('staff_register/', staff_register_view, name="staff_register"),
]

IABC_WEB/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'IABC_WEB'

urlpatterns = [
    path('my_account/<acc_id>$/', views.my_account, name='my_account'),
    path('view_profile/<acc_id>$/', views.view_profile, name='view_profile'),
    path('edit_profile/<acc_id>$/', views.edit_profile, name='edit_profile'),
    path('userawards_proof/<acc_id>$/', views.userawards_proof, name='userawards_proof'),
    path('userawards_proofupload/<acc_id>$/', views.userawards_proofupload, name='userawards_proofupload'),
    path('userawards_proofupload2/<acc_id>$/', views.userawards_proofupload2, name='userawards_proofupload2'),
    path('userawards_proofdel/<acc_id>$/', views.userawards_proofdel, name='userawards_proofdel'),
    path('userawards_proofdel2/<acc_id>$/', views.userawards_proofdel2, name='userawards_proofdel2'),
    path('usermembers_proof/<acc_id>$/', views.usermembers_proof, name='usermembers_proof'),
    path('usermembers_proofupload/<acc_id>$/', views.usermembers_proofupload, name='usermembers_proofupload'),
    path('usermembers_proofdel/<acc_id>$/', views.usermembers_proofdel, name='usermembers_proofdel'),
    path('usertransachistory/<acc_id>$/', views.usertransachistory, name='usertransachistory'),
    path('renewalproof/<acc_id>$/', views.renewalproof, name='renewalproof'),
    path('renewalproofupload/<acc_id>$/', views.renewalproofupload, name='renewalproofupload'),
    path('renewalproofdelete/<acc_id>$/', views.renewalproofdelete, name='renewalproofdelete'),

    path('downloadables/', views.downloadables, name='downloadables'),
    path('eventsview/', views.eventsview, name='eventsview'),
    path('awardsabout1/', views.awardsabout1, name='awardsabout1'),
    path('awardsabout2/', views.awardsabout2, name='awardsabout2'),
    path('awardsabout3/', views.awardsabout3, name='awardsabout3'),
    path('awardsabout4/', views.awardsabout4, name='awardsabout4'),
    path('membenefits/', views.membenefits, name='membenefits'),
    path('whyiabc/', views.whyiabc, name='whyiabc'),


    path('awardspaid/', views.awardspaid, name='awardspaid'),
    path('awardspaid_details/<ent_id>$/', views.awardspaid_details, name='awardspaid_details'),
    path('awardspaid_details2/<ent_id>$/', views.awardspaid_details2, name='awardspaid_details2'),
    path('awardspaid_del/<awardspaid_id>$/', views.awardspaid_del, name='awardspaid_del'),

    path('awardspending/', views.awardspending, name='awardspending'),
    path('awardspending_details/<ent_id>$/', views.awardspending_details, name='awardspending_details'),
    path('awardspending_details2/<ent_id>$/', views.awardspending_details2, name='awardspending_details2'),
    path('awardspending_edit/<ent_id>$/', views.awardspending_edit, name='awardspending_edit'),
    path('awardspending_edit2/<ent_id>$/', views.awardspending_edit2, name='awardspending_edit2'),
    path('awardspending_del/<awardspend_id>$/', views.awardspending_del, name='awardspending_del'),
    
    path('awardsform/', views.awardsform, name='awardsform' ),
    path('awardsform2/', views.awardsform2, name='awardsform2' ),
    path('attach/', views.attach, name='attach' ),
    path('aebill_pdf/', views.aebill_pdf, name='aebill_pdf' ),
    path('awardssubmit/', views.awardssubmit, name='awardssubmit' ),


    path('memberapp/', views.memberapp, name='memberapp' ),
    path('membersubmit/', views.membersubmit, name='membersubmit' ),
    path('memberform2/', views.memberform2, name='memberform2' ),
    path('attach2/', views.attach2, name='attach2' ),
    path('memebill_pdf/', views.memebill_pdf, name='memebill_pdf' ),
    path('paymentopt/', views.paymentopt, name='paymentopt' ),
    path('paymentoptmember/', views.paymentoptmember, name='paymentoptmember' ),
    path('onlinepay/', views.onlinepay, name='onlinepay' ),
    path('overtc/', views.overtc, name='overtc' ),
    path('check/', views.check, name='check' ),
    path('admember/', views.admember, name='admember' ),
    path('pendmember/', views.pendmember, name='pendmember' ),
    path('viewmember/<viewmem_id>$/', views.viewmember, name='viewmember' ),
    path('editviewmember/<editviewmem_id>$/', views.editviewmember, name='editviewmember' ),
    path('viewpendmember/<viewpendmem_id>$/', views.viewpendmember, name='viewpendmember' ),
    path('editpendmember/<editpendmem_id>$/', views.editpendmember, name='editpendmember' ),
    path('member_del/<mem_id>$/', views.member_del, name='member_del' ),
    path('pendmember_del/<pendmem_id>$/', views.pendmember_del, name='pendmember_del' ),
    path('nonmember/', views.nonmember, name='nonmember' ),
    path('nonmember_view/<non_id>$/', views.nonmember_view, name='nonmember_view' ),
    path('nonmember_edit/<non_id>$/', views.nonmember_edit, name='nonmember_edit' ),
    path('nonmember_del/<non_id>$/', views.nonmember_del, name='nonmember_del' ),
    path('user_del/<user_id>$/', views.user_del, name='user_del' ),
    path('adrenewal/', views.adrenewal, name='adrenewal' ),
    path('adminrenewalproof/<mem_id>$/', views.adminrenewalproof, name='adminrenewalproof' ),
    path('membcom/', views.membcom, name='membcom' ),


    path('renewform/', views.renewform, name='renewform' ),
    path('renewattach/', views.renewattach, name='renewattach' ),
    path('renewbill_pdf/', views.renewbill_pdf, name='renewbill_pdf' ),
    path('paymentoptrenew/', views.paymentoptrenew, name='paymentoptrenew' ),
    path('onlinepayrenew/', views.onlinepayrenew, name='onlinepayrenew' ),
    path('overtcrenew/', views.overtcrenew, name='overtcrenew' ),
    path('checkrenew/', views.checkrenew, name='checkrenew' ),

    path('delproj_trac/<ent_id>$/', views.delproj_trac, name='delproj_trac' ),
    path('delproj_trac2/<ent_id>$/', views.delproj_trac2, name='delproj_trac2' ),
    path('editproj/<proje_id>$/', views.editproj, name='editproj' ),
    path('addproj/<proje_id>$/', views.addproj, name='addproj' ),
    path('view_bidders/', views.view_bidders, name='view_bidders' ),
    path('bidder_del/<bid_id>$/', views.bidder_del, name='bidder_del' ),
    path('bidder_dashboard/', views.bidder_dashboard, name='bidder_dashboard' ),
    path('bidder_app/', views.bidder_app, name='bidder_app' ),
    path('biddersubmit/', views.biddersubmit, name='biddersubmit' ),
    path('bidderviewprop/<bid_id>$/', views.bidderviewprop, name='bidderviewprop' ),
    path('bidderremark/<bid_id>$/', views.bidderremark, name='bidderremark' ),
    path('bidderstatus/<bid_id>$/', views.bidderstatus, name='bidderstatus' ),
    path('bidderprop_del/<bid_id>$/', views.bidderprop_del, name='bidderprop_del' ),
    path('viewproj_track/', views.viewproj_track, name='viewproj_track' ),
    path('viewproj_track2/<proje_id>$/', views.viewproj_track2, name='viewproj_track2' ),
    path('checklist/<proje_id>$/', views.checklist, name='checklist' ),
    path('proj_remarks/<proje_id>$/', views.proj_remarks, name='proj_remarks' ),
    path('act_list/', views.act_list, name='act_list' ),

    path('chartA/', views.chartA, name='chartA' ),
    path('chartB/', views.chartB, name='chartB' ),
    path('chartC/', views.chartC, name='chartC' ),
    path('chartD/', views.chartD, name='chartD' ),
    path('chartE/', views.chartE, name='chartE' ),
    path('chartF/', views.chartF, name='chartF' ),
    path('chartG/', views.chartG, name='chartG' ),
    path('chart_Add/', views.chart_Add, name='chart_Add' ),

    path('chartA_del/<cht_id>$/', views.chartA_del, name='chartA_del' ),
    path('chartB_del/<cht_id>$/', views.chartB_del, name='chartB_del' ),
    path('chartC_del/<cht_id>$/', views.chartC_del, name='chartC_del' ),
    path('chartD_del/<cht_id>$/', views.chartD_del, name='chartD_del' ),
    path('chartE_del/<cht_id>$/', views.chartE_del, name='chartE_del' ),
    path('chartF_del/<cht_id>$/', views.chartF_del, name='chartF_del' ),
    path('chartG_del/<cht_id>$/', views.chartG_del, name='chartG_del' ),

    path('awardscrud/', views.awardscrud, name='awardscrud'),
    path('category/', views.category, name='category'),
    path('certification/', views.certification, name='certification'),
    path('division/', views.division, name='division'),
    path('div_del/<cht_id>$/', views.div_del, name='div_del' ),
    path('categ_del/<cht_id>$/', views.categ_del, name='categ_del' ),
    path('cert_del/<cht_id>$/', views.cert_del, name='cert_del' ),

    path('winners/', views.winners, name='winners'),
    path('winnersCat/', views.winnersCat, name='winnersCat'),
    path('winnersdel/<del_id>$/', views.winnersdel, name='winnersdel'),
    path('winners2/', views.winners2, name='winners2'),
    path('winnersCat2/', views.winnersCat2, name='winnersCat2'),
    path('winnersdel2/<del_id>$/', views.winnersdel2, name='winnersdel2'),
    path('studwinners_pdf/', views.studwinners_pdf, name='studwinners_pdf' ),
    path('profwinners_pdf/', views.profwinners_pdf, name='profwinners_pdf' ),
    path('viewwinners/', views.viewwinners, name='viewwinners'),

    path('price/', views.price, name='price'),
    path('pricedel/<del_id>$/', views.pricedel, name='pricedel'),
    path('admintransachistory/', views.admintransachistory, name='admintransachistory'),

    path('awardspaid_pdf/', views.awardspaid_pdf, name='awardspaid_pdf' ),
    path('awardspending_pdf/', views.awardspending_pdf, name='awardspending_pdf' ),

    path('memreport/', views.memreport, name='memreport'),
    path('pendmemreport/', views.pendmemreport, name='pendmemreport'),
    path('membersgen/', views.membersgen, name='membersgen'),
    path('awardspaidgen/', views.awardspaidgen, name='awardspaidgen'),
    path('winnersprofgen/', views.winnersprofgen, name='winnersprofgen'),
    path('winnersstudgen/', views.winnersstudgen, name='winnersstudgen'),
    path('transacgen/', views.transacgen, name='transacgen'),





]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \

members/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import PasswordsChangeView

app_name = 'members'

urlpatterns = [
    path('login_user', views.login_user, name="login"),
    path('logout_user', views.logout_user, name="logout"),
    path('', views.home, name='home'),
    path('password_change/', PasswordsChangeView.as_view(template_name='user-changepassword.html'), name = 'password_change' ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

IABC_WEB/templates/admin-awardspending.html
{% load static %} 

<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/admindata.css' %}">
    <script src="{% static 'js/admin.js' %}"></script>

    <title>IABC PHILIPPINES</title>
    <link rel = "icon" href="{% static 'img/logo.png' %}" type = "image/x-icon">

    <style>
      #remarks2 {
        width: 120px;
        height: 30px;
        border: 1px solid #ccc;
          border-radius: 8px;
          color:#6e6e6e;
        text-indent: 2px;
          font-size: 14px;
      }

      #remarks2:focus {
          -moz-box-shadow: none !important;
          -webkit-box-shadow: none !important;
          box-shadow: none !important;
          border: 1px solid  #2a7221;
          outline-width: 0;
      }

      .gen {
          width: 70px;
          height: 28px;
          border: 1px solid #2a7221;
          background: #2a7221;
          text-align: center;
          color: #fff;
          border-radius: 10px;
          cursor: pointer;
          font-size: 13px;
      }
</style>

</head>
<body>
    <!--<nav class="nav justify-content-end">
    <a class="nav-link" href="{% url 'members:logout' %}">LOGOUT</a>
  </nav>-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand " style="margin-left: 120px;" href="{% url 'members:home' %}">
            <img src="{%static 'img/logo1.png' %}" height="80" width="300">
        </a>
        <nav class="stroke" style="margin-right: 120px;">
          <ul>
            {% if info.is_admin == True %}
            <li><a href="{% url 'IABC_WEB:admember' %}">Members</a></li>
            {% else %}
                <li></li>
                {% endif %}
            {% if info.is_admin or info.is_staff == True %}
            <li><a href="{% url 'IABC_WEB:awardspaid' %}">PhilQuill Entries</a></li>
            {% else %}
                <li></li>
                {% endif %}
            {% if info.is_admin == True %}
            <li><a href="{%url 'IABC_WEB:admintransachistory' %}">Transaction History</a></li>
            {% else %}
                <li></li>
                {% endif %}
            {% if info.is_admin or info.is_staff == True %}
                
            <li class="dropdown"><a href="#">Events<ion-icon name="caret-down-outline"></ion-icon></a>
                <ul class="dropdown-content"> 
                    {% if info.is_admin == True %}
                  <li><a href="{% url 'IABC_WEB:view_bidders' %}">Bidders</a></li>
                  {% else %}
                <li></li>
                {% endif %}
                  <li><a href="{% url 'IABC_WEB:viewproj_track' %}">Project Tracker</a></li>
                </ul>
            </li>
            {% else %}
                <li></li>
            {% endif %}
            {% if info.is_admin or info.is_staff == True %}
            <li class="dropdown"><a href="#"><img src="{%static 'img/gear-solid.svg' %}" height="20" width="20"></a>
              <ul class="dropdown-content2" style="right: 0px; width: 200px;">
                {% if info.is_admin or info.is_staff == True %}
                <li><a href="{% url 'IABC_WEB:act_list' %}">Activity CRUD</a></li>
                {% else %}
                <li></li>
                {% endif %}
                {% if info.is_admin or info.is_staff == True %}
                <li><a href="{% url 'IABC_WEB:awardscrud' %}">Awards CRUD</a></li>
                {% else %}
                <li></li>
                {% endif %}
                {% if info.is_admin or info.is_staff == True %}
                <li><a href="{% url 'IABC_WEB:chartA' %}">Charts CRUD</a></li>
                {% else %}
                <li></li>
                {% endif %}
                {% if info.is_admin == True %}
                <li><a href="{% url 'IABC_WEB:price' %}">Product Prices CRUD</a></li>
                {% else %}
                <li></li>
                {% endif %}
                {% if info.is_admin == True %}
                <li><a href="{% url 'bidder_register' %}">Create Bidders Account</a></li>
                <li><a href="{% url 'staff_register' %}">Create Staffs Account</a></li>
                {% else %}
                <li></li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            <li class="dropdown"><a href="{% url 'members:logout' %}"><img src="{%static 'img/logout.svg' %}" height="20" width="20"></a></li>
          </ul>
        </nav>
    </div>
  </nav>
    
    <div class="container-fluid1 justify-content-end">
        <div>
            <h2><strong>AWARDS ENTRIES</strong></h2>
            <p style="border-style: solid; width: 100px; color: #2a7221;">
        </div>

        <div class="row home justify-content-between mt-5">
          <div class="col-sm-12 col-md-3 col-lg-3">
            <a class="btn btn1 mb-3" href="{% url 'IABC_WEB:awardspaid' %}" role="button"><i class="fa fa-user-check"></i>&nbsp;&nbsp;Paid Entries</a><br>
            <a class="btn btn-primary mb-3" href="{% url 'IABC_WEB:awardspending' %}" role="button"><i class="fa fa-user-clock"></i>&nbsp;&nbsp;Pending Entries</a><br>
            <a class="btn btn1 mb-3" href="{%url 'IABC_WEB:winnersCat2' %}" role="button"><i class="fa fa-trophy"></i>&nbsp;&nbsp;Professional Winners</a><br>
            <a class="btn btn1 mb-3" href="{% url 'IABC_WEB:winnersCat' %}" role="button"><i class="fa fa-trophy"></i>&nbsp;&nbsp;Student Winners</a><br>
          </div>

          
              
           

            <div class="col-sm-12 col-md-8 col-lg-8 align-self-end">
                <div class="wrap">
                  <form method="POST" action="{% url 'IABC_WEB:awardspending_pdf' %}">{% csrf_token %}
                    <select id="remarks2" name="filt" >
                      <option value="All">All</option>
                      <option value="Today">Today</option>
                      <option value="Last 7 Days">Last 7 Days</option>
                      <option value="Last 30 Days">Last 30 Days</option>
                    </select>
                    <button type="submit" formtarget="_blank" class="gen">
                      <i class="fa fa-print"></i>&ensp;Print
                    </button> 
                  </form>
                    <div class="search">
                       <input type="text" class="searchTerm" placeholder="Search">
                       <button type="submit" class="searchButton">
                          <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
                <div class="row justify-content-between">
                    <section>
                        <div class="tbl-header" >
                          <table cellpadding="0" cellspacing="0" border="0">
                            <thead>
                              <tr>
                                <th width="5%"></th>
                                <th width="10%" class="thheading">Entry No.</th>
                                <th width="21%" class="thheading">Name</th>
                                <th width="24%" class="thheading">Entry Name</th>
                                <th width="20%" class="thheading">Division</th>
                                <th width="10%" class="thheading">Details</th>
                                <th width="10%" class="thheading">Status</th>
                              </tr>
                            </thead>
                          </table>
                        </div>
                        <div class="tbl-content">
                          <table cellpadding="0" cellspacing="0" border="0">
                            <tbody>
                              {% if awardsstudentpending or awardsprofpending %}
                                {% for award in awardsstudentpending %}
                              <tr>
                                <form action="{% url 'IABC_WEB:awardspending_del' award.id %}"  method="POST" enctype="multipart/form-data"> {% csrf_token %}
                                    <td width="5%"><button type="submit" name="awardstud" class="btndelete" ><i class="fa fa-trash"></i></button></td>
                                    <td width="10%">{{ award.id }}</td>
                                    <td width="21%" class="tdcell">{{ award.entrant_name }}</td>
                                    <td width="24%">{{ award.entry_title }}</td>
                                    <td width="20%">{{ award.division }}</td>
                                    <td width="10%"><a class="a-tbl" href="{% url 'IABC_WEB:awardspending_details' award.id %}">View Details</a></td>
                                    <td width="10%"class="fst-italic">Pending</td>
                                  </form>
                              </tr>
                              {% endfor %}
                              {% for awards in awardsprofpending %}
                              <tr>
                                <td width="5%"><a href="{% url 'IABC_WEB:awardspending_del' awards.id %}" type="button" name="awardsprof" class="btndelete" ><i class="fa fa-trash"></i></button></td>
                                <td width="10%">{{ awards.id }}</td>
                                <td width="21%" class="tdcell">{{ awards.entrant_name }}</td>
                                <td width="24%">{{ awards.entry_title }}</td>
                                <td width="20%">{{ awards.division }}</td>
                                <td width="10%"><a class="a-tbl" href="{% url 'IABC_WEB:awardspending_details2' awards.id %}">View Details</a></td>
                                <td width="10%"class="fst-italic">Pending</td>
                              </tr>
                              {% endfor %}
                              {% else %}
                                <tr>
                                  <td width="100%"class="fst-italic">No entries Yet</td>
                                </tr>
                            {% endif %}
                             
                            </tbody>
                          </table>
                        </div>
                      </section>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

IABC_WEB/templates/awards-ebillstudent.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	
		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
		<!-- <link rel="stylesheet" type="text/css" href="{%static 'css/users.css' %}"> -->
	
		<title>IABC PHILIPPINES</title>
		<link rel = "icon" href="{%static 'img/logo.png' %}" type = "image/x-icon">
	</head>
<style>
@page{
		size: 8.31in 11.7in;
		margin: 15mm 20mm 10mm 20mm;
}
body {
  font-size: 130%;
}
</style>
<body>
	{% block content %}
	<table align=center width="700">
		<tr>
			<td width="190" align=left><img src="{%static 'img/logo.png' %}" height="80" width="300"></td>
			<td width="320" align=center><p> IABC PHILIPPINES INC. <br>
						No. 136 Yakal St. San Antonio Village Makati City <br>
						City of Makati, NCR, Fourth Disctrict, Philippines<br>
						Tel. nos: 756-0441 or 756-0424 (Telefax)<br>
						Email: iabcphilippinesat30@gmail.com <br>
						Website: www.iabcphilippines.com<br>
						VAT REG TIN 007-559-027-00000</p></td>
		</tr>
		<tr>
			<td colspan=3 align=center><br><strong><h2>E-BILLING STATEMENT</strong><br></td></h2>
		</tr>
	</table>
	
	<br>
	
	
	<hr color="#F8F8F8">
	
	<table align=center width="800" >
		<tr>
			<td width="150" colspan="3"><p>To:{{comp}}</p></td>
		</tr>
	
		<tr>
			<td width="150" colspan="3"><p>Address:{{address}}</p></td>
	
		</tr>
	
		<tr>
			<td width="150">TIN:{{tin}}</td>
			<td colspan="3">Business Name / Style</td>
		</tr>
	
	
		<tr>
			<td width="120"><p>Date:{{dates}}</p></td>
			<td width="120"><p>J.O NO.:</p></td>
			<td width="120"><p>CES NO.</p></td>
	
	
		</tr>
	</table>
	
	
	
	
	
	
	
	<hr> 
	
		<br>
	<table align="center">
		<tr>
			<td width="120" align="center"><p>DESCRIPTION:</p></td>
			<td width="600" align="right"><p>AMOUNT</p></td>
		</tr>
	</table>
	
	<br><br>
	
			<div style= "font-size: 80%";>
			<p>ATTN: {{contp}}</p>
	
			</div>
	<br><br>
	
	
	
		<table align="center">
			<tr>
				<td width="550" align="left"><p>19TH PHILIPPINES QUILL AWARDS</p></td>
				<td width="200" align="right"><p>500.00</p></td>
	
			</tr>
			<tr>
				<td width="550" align="left" colspan="2"><i>ENTRY FEE</i></td>
			</tr>
	
			<tr>
				<td height="20" colspan="2"></td>
			</tr>
	
	
			<tr> 
				<td width="10" colspan="2">(Php 500 regular rate for Student) <br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i>VAT-Inclusive</i> </td>
			</tr>
		</table>
	<br><br><br><br><br><br>
	
	
	
				<div style="text-align: center; font-size: 80%";>
					NOTE: Please make check payable to IABC PHILIPPINES, INC.
				</div>
	
	
	
	
	<!--end-->
	
	
	<!--end of table-->
	<br>
	
	{% endblock %}
</body>
</html>